### ISSUE TITLE
Bug when using "const char" pointers in a function argument declaration

### ISSUE THREAD

**Issue by nibblebits** [nibblebits/DragonCompiler#26]
```
int printf(const char* msg, int m)
{

}
```

causes a segmentation fault.
```
program received signal SIGSEGV, Segmentation fault.
0x0000555555558f4c in parser_scope_offset_for_stack (node=0x55555557b900, history=0x55555557b8e0) at parser.c:254
254	    if (!variable_node_is_primative(node) && variable_struct_node(node)->_struct.body_n->body.padded)
(gdb) bt
#0  0x0000555555558f4c in parser_scope_offset_for_stack (node=0x55555557b900, history=0x55555557b8e0) at parser.c:254
#1  0x00005555555590cd in parser_scope_offset (node=0x55555557b900, history=0x55555557b8e0) at parser.c:299
#2  0x000055555555c5c0 in parse_variable (dtype=0x7fffffffda50, name_token=0x5555555747a0, history=0x55555557b8e0)
    at parser.c:1690
#3  0x000055555555c68d in parse_variable_full (history=0x55555557b8e0) at parser.c:1710
#4  0x000055555555c708 in parse_function_arguments (history=0x55555557a0c0) at parser.c:1725
#5  0x000055555555c828 in parse_function (dtype=0x7fffffffdb70, name_token=0x555555574740, history=0x555555579f20)
    at parser.c:1761

```

**Comment by nibblebits** [comment]
Fixed: https://github.com/nibblebits/DragonCompiler/commit/bcaaadac76e4746424fc42d80291f0382e97a563
